// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuFwD1YjfXgYYI4osxOD0tZuo6_H0bJoc',
    appId: '1:372128454670:web:cb93d4e21fe403e823845f',
    messagingSenderId: '372128454670',
    projectId: 'omkar-149d8',
    authDomain: 'omkar-149d8.firebaseapp.com',
    storageBucket: 'omkar-149d8.appspot.com',
    measurementId: 'G-SMBKZR4VP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbSfyCAf8o74nBTtZ6mKc7_LEt_wsqA4',
    appId: '1:372128454670:android:25a662299fa38b4423845f',
    messagingSenderId: '372128454670',
    projectId: 'omkar-149d8',
    storageBucket: 'omkar-149d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChkUV-oZGJ9CU5oaoLCKdmNcl8yKpBpcA',
    appId: '1:372128454670:ios:11d1752fef242c2c23845f',
    messagingSenderId: '372128454670',
    projectId: 'omkar-149d8',
    storageBucket: 'omkar-149d8.appspot.com',
    iosBundleId: 'com.example.onlineDoctorBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChkUV-oZGJ9CU5oaoLCKdmNcl8yKpBpcA',
    appId: '1:372128454670:ios:11d1752fef242c2c23845f',
    messagingSenderId: '372128454670',
    projectId: 'omkar-149d8',
    storageBucket: 'omkar-149d8.appspot.com',
    iosBundleId: 'com.example.onlineDoctorBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuFwD1YjfXgYYI4osxOD0tZuo6_H0bJoc',
    appId: '1:372128454670:web:cc41fd759485699f23845f',
    messagingSenderId: '372128454670',
    projectId: 'omkar-149d8',
    authDomain: 'omkar-149d8.firebaseapp.com',
    storageBucket: 'omkar-149d8.appspot.com',
    measurementId: 'G-W8YZ0RJM2G',
  );
}
